import type { Compra, Estoque } from '../types';

const hoje = new Date();
const d = (offset: number) => {
  const dt = new Date(hoje);
  dt.setDate(dt.getDate() - offset);
  return dt.toISOString();
};

export const SEED_COMPRAS: Compra[] = [
  {
    id: 'seed-1',
    produto: 'Arroz 5kg',
    categoria: 'Alimentação',
    essencial: true,
    quantidade: 1,
    unidade: 'un',
    valorUni: 28.90,
    valorTotal: 28.90,
    mercado: 'Atacadão',
    data: d(0),
  },
  {
    id: 'seed-2',
    produto: 'Leite Integral',
    categoria: 'Laticínios',
    essencial: true,
    quantidade: 4,
    unidade: 'un',
    valorUni: 5.70,
    valorTotal: 22.80,
    mercado: 'Mercado A',
    data: d(0),
  },
  {
    id: 'seed-3',
    produto: 'Detergente Ypê',
    categoria: 'Limpeza',
    essencial: true,
    quantidade: 3,
    unidade: 'un',
    valorUni: 3.90,
    valorTotal: 11.70,
    mercado: 'Mercado A',
    data: d(1),
  },
  {
    id: 'seed-4',
    produto: 'Salgadinho Ruffles',
    categoria: 'Não Essencial',
    essencial: false,
    quantidade: 2,
    unidade: 'un',
    valorUni: 9.80,
    valorTotal: 19.60,
    mercado: 'Mercado A',
    data: d(1),
  },
  {
    id: 'seed-5',
    produto: 'Feijão Carioca 1kg',
    categoria: 'Alimentação',
    essencial: true,
    quantidade: 2,
    unidade: 'kg',
    valorUni: 8.50,
    valorTotal: 17.00,
    mercado: 'Atacadão',
    data: d(2),
  },
  {
    id: 'seed-6',
    produto: 'Shampoo Seda',
    categoria: 'Higiene',
    essencial: true,
    quantidade: 1,
    unidade: 'un',
    valorUni: 14.90,
    valorTotal: 14.90,
    mercado: 'Farmácias',
    data: d(3),
  },
  {
    id: 'seed-7',
    produto: 'Frango inteiro',
    categoria: 'Carnes',
    essencial: true,
    quantidade: 2,
    unidade: 'kg',
    valorUni: 18.50,
    valorTotal: 37.00,
    mercado: 'Atacadão',
    data: d(3),
  },
  {
    id: 'seed-8',
    produto: 'Tomate cereja',
    categoria: 'Hortifruti',
    essencial: true,
    quantidade: 0.5,
    unidade: 'kg',
    valorUni: 15.80,
    valorTotal: 7.90,
    mercado: 'Feira',
    data: d(5),
  },
  {
    id: 'seed-9',
    produto: 'Macarrão Barilla',
    categoria: 'Alimentação',
    essencial: true,
    quantidade: 3,
    unidade: 'un',
    valorUni: 6.90,
    valorTotal: 20.70,
    mercado: 'Mercado A',
    data: d(5),
  },
  {
    id: 'seed-10',
    produto: 'Ariel 1kg',
    categoria: 'Limpeza',
    essencial: true,
    quantidade: 1,
    unidade: 'kg',
    valorUni: 38.90,
    valorTotal: 38.90,
    mercado: 'Atacadão',
    data: d(7),
  },
  {
    id: 'seed-11',
    produto: 'Cerveja Heineken',
    categoria: 'Não Essencial',
    essencial: false,
    quantidade: 6,
    unidade: 'un',
    valorUni: 6.30,
    valorTotal: 37.80,
    mercado: 'Mercado A',
    data: d(8),
  },
  {
    id: 'seed-12',
    produto: 'Dipirona 500mg',
    categoria: 'Farmácia',
    essencial: true,
    quantidade: 1,
    unidade: 'cx',
    valorUni: 12.90,
    valorTotal: 12.90,
    mercado: 'Farmácias',
    data: d(10),
  },
  {
    id: 'seed-13',
    produto: 'Queijo Mussarela',
    categoria: 'Laticínios',
    essencial: true,
    quantidade: 0.4,
    unidade: 'kg',
    valorUni: 49.90,
    valorTotal: 19.96,
    mercado: 'Atacadão',
    data: d(12),
  },
  {
    id: 'seed-14',
    produto: 'Azeite Gallo 500ml',
    categoria: 'Alimentação',
    essencial: true,
    quantidade: 1,
    unidade: 'un',
    valorUni: 27.50,
    valorTotal: 27.50,
    mercado: 'Atacadão',
    data: d(14),
  },
  {
    id: 'seed-15',
    produto: 'Biscoito Oreo',
    categoria: 'Não Essencial',
    essencial: false,
    quantidade: 2,
    unidade: 'pct',
    valorUni: 8.90,
    valorTotal: 17.80,
    mercado: 'Mercado A',
    data: d(15),
  },
];

export const SEED_ESTOQUE: Estoque[] = [
  {
    id: 'est-1',
    produto: 'Papel Higiênico',
    qtdAtual: 1,
    qtdMinima: 4,
    unidade: 'un',
    ultimaCompra: d(20),
  },
  {
    id: 'est-2',
    produto: 'Arroz 5kg',
    qtdAtual: 1,
    qtdMinima: 2,
    unidade: 'un',
    ultimaCompra: d(0),
  },
  {
    id: 'est-3',
    produto: 'Café Pilão',
    qtdAtual: 1,
    qtdMinima: 2,
    unidade: 'pct',
    ultimaCompra: d(15),
  },
  {
    id: 'est-4',
    produto: 'Feijão',
    qtdAtual: 2,
    qtdMinima: 1,
    unidade: 'kg',
    ultimaCompra: d(2),
  },
  {
    id: 'est-5',
    produto: 'Detergente',
    qtdAtual: 3,
    qtdMinima: 2,
    unidade: 'un',
    ultimaCompra: d(1),
  },
  {
    id: 'est-6',
    produto: 'Sabão em Pó',
    qtdAtual: 1,
    qtdMinima: 1,
    unidade: 'kg',
    ultimaCompra: d(7),
  },
];
